
#ifndef __EMEDIA_DEFINES_H__
#define __EMEDIA_DEFINES_H__

typedef enum{
    EMSTREAM_TYPE_NORMAL = 0,
    EMSTREAM_TYPE_DESKTOP = 1,
}EMediaStreamType;

typedef enum{
    EMEDIA_ERROR_NONE = 0,
    EMEDIA_ERROR_UNKNOWN = -1,
    
    EMEDIA_ERROR_INVALID_ARG = -102,
    EMEDIA_ERROR_CANCEL = -106,
    EMEDIA_ERROR_NO_NET = -108,
    
    EMEDIA_ERROR_CONN_TIMEOUT = -102,
    EMEDIA_ERROR_JOIN_TIMEOUT = -103,
    
    EMEDIA_ERROR_ALREADY_JOIN = -122,
    EMEDIA_ERROR_ALREADY_PUBLISH = -123,
    EMEDIA_ERROR_ALREADY_SUBSCRIBE = -124,
    
    EMEDIA_ERROR_NO_SESSION = -142,
    EMEDIA_ERROR_NO_PUBLISH = -143,
    EMEDIA_ERROR_NO_SUBSCRIBE = -144,
    EMEDIA_ERROR_NO_STREAM = -145,
    
    EMEDIA_ERROR_REASON_HANGUP = -400,
    EMEDIA_ERROR_REASON_NORESPONSE = -401,
    EMEDIA_ERROR_REASON_REJECT = -402,
    EMEDIA_ERROR_REASON_BUSY = -403,
    EMEDIA_ERROR_REASON_FAIL = -404,
    EMEDIA_ERROR_REASON_UNSUPPORTED = -405,
    EMEDIA_ERROR_REASON_OTHER_DEVICE = -410,
    EMEDIA_ERROR_REASON_DISMISS = -411,
    
    
    EMEDIA_ERROR_TICKET_INVALID = -500,
    EMEDIA_ERROR_TICKET_EXPIRED = -502,
    EMEDIA_ERROR_SESSION_EXPIRED = -504,
    EMEDIA_ERROR_NONEXIST_CONFERENCE = -506,
    
    EMEDIA_ERROR_MAX = -99999
    
}EMediaErrorCode;

typedef enum{
    EMEDIA_NOTICE_NONE = 0,
    EMEDIA_NOTICE_DISCONN = 120,
    EMEDIA_NOTICE_RECONN = 121,
    EMEDIA_NOTICE_POOR_QUALITY = 122,
    EMEDIA_NOTICE_PUBLISH_SETUP = 123, //发布成功
    EMEDIA_NOTICE_SUBSCRIPTION_SETUP = 124, //连接建立,返回streamId
}EMediaNoticeCode;


// TODO: sync with web and server
typedef enum{
//    EMEDIA_REASON_NOTUSED = -1,
    EMEDIA_REASON_NORMAL = 0,
//    EMEDIA_REASON_NORESPONSE = 1,
//    EMEDIA_REASON_REJECT = 2,
//    EMEDIA_REASON_BUSY = 3,
//    EMEDIA_REASON_FAIL = 4,
//    EMEDIA_REASON_UNSUPPORTED = 5,
//    EMEDIA_REASON_OTHER_DEVICE = 100,
//    EMEDIA_REASON_DISMISS = 101,
//    EMEDIA_REASON_KICKTIMEOUT = 102,
//    EMEDIA_REASON_UNKNOWN = 199,
//    
//    EMEDIA_REASON_LOCAL_DISCONN = 201,
//    EMEDIA_REASON_LOCAL_TIMEOUT = 202,
//    EMEDIA_REASON_MAX = 10000
}EMediaReasonType;


#endif






